### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by umitkucuk** [umitkucuk/vue-playground#2]
- [x] Fetched data is not sequential
- [x] Loading state doesn't seem to work when navigating between pages (it works when refreshing the current page) c293db8965068d27a31a7c3c12506a43f7b220f1
- [x] Active tab won't set correctly on the navigation if the current page is refreshed cc3b1bfeeca406bc4480f77138df37e9e9734b23
- [x] Server is rendering all element-ui styles (it should render styles which are necessary)

**Comment by buremba** [comment]
1. Could you please clarify the `sequential` part? They have an `id` attribute that you can use as a unique identifier of the rows.
2. The loading state is used by Nuxt.js when it's rendering the page components. You're responsible from the internal loading state of your component. You may use Element UI's loading state in order to show the loading icon before the content is fetched and rendered. I see that you're using your custom loading component but it doesn't seem to work.
3. You need to set `activeIndex` variable at initialization in your `Header` component. 
4. That's OK, typically Webpack handles it for you in production.

**Comment by umitkucuk** [comment]
1. Here is a screenshot about this issue below. Fetched data is on the left and data that I want to fetch is on the right. As you can see from the ss, "Glovebox" has different ID(it's ID is 2 instead of 7) in fetched data.

![ss](https://user-images.githubusercontent.com/24843599/42439512-c99b427a-836b-11e8-9a4e-46c04fa0a1bf.PNG)

**Comment by buremba** [comment]
You don't need to worry about the ordering for 1.

P.S: You can also use task lists in issues, once you complete them you can click the box, Github UI works better in this way.
